import esbuild from "esbuild";
import fs from "fs/promises";

esbuild
  .build({
    entryPoints: ["worker/docnode-worker.ts"],
    bundle: true,
    format: "iife", // Inline Immediately Invoked Function Expression
    outfile: "./dist/worker/docnode-worker.js",
    platform: "browser",
    globalName: "inlinedCode", // Optional: name of the global variable
  })
  .then(async () => {
    const workerCode = await fs.readFile(
      "./dist/worker/docnode-worker.js",
      "utf-8",
    );
    const header = `/* eslint-disable */
// @ts-nocheck
/**
 * This file is generated by docnode. Do not edit it directly.
 */

    `;
    const newWorkerCode = header + workerCode;
    await fs.writeFile("../../docs/public/docnode-worker.js", newWorkerCode);
    console.log("Bundling completed successfully!");
  })
  .catch((err) => {
    console.error("Error during bundling:", err);
  });
